vim-jp/ekiden

src/content.json

fix: correction of URL

---

LICENSE.txt
README.md

ref: #50 
CC-BY 4.0 でどうでしょう？
ライセンスファイルや README の文言は https://github.com/vim-jp/vim-jp.github.io を~パク~参考にしました。

[proposal] Apply CC-BY 4.0 license

---

pnpm-lock.yaml
src/components/Footer.astro
src/layouts/Base.astro

[Add] フッターとライセンスの追加

---

scripts/update-article.ts
src/components/Article.astro
src/components/Articles.astro
src/content.json
src/pages/archive.astro
src/pages/rss.xml.ts

Closes #106
お願い: 誰かが参加登録等をして content.json が更新されるとコンフリクトになるので、迅速にマージしたいです。

Call "author" as "runner"

---

src/content.json

すみません、本文側のタイトルを直してIssueのタイトルを直すの忘れてました。

fix title of the 2023-10-09

---

src/content.json

100回目おめでとうございます。自分のウェブサイトの生成ツールを変えた影響でリンクが死んでしまったので、更新のほどよろしくお願いします。

Remove suffix (tani's articles)

---

.github/workflows/deploy.yml

今度こそ（3度目の正直）
一応forkしたリポジトリで動くの確認できました

fix: ci fail

---

.github/dependabot.yml

npm(pnpm) / actionsを対象に作成、頻度は週次としています

Create dependabot.yml to also checking actions versions

---

.github/workflows/deploy.yml

ビルドがコケたのでRevert https://github.com/vim-jp/ekiden/actions/runs/7463869174
Reverts vim-jp/ekiden#230

Revert "Bump actions/deploy-pages from 1 to 4"

---

.github/workflows/deploy.yml

#230 で失敗したアップグレードを部分的に実行
ref: https://github.com/withastro/action/pull/38

Bump actions/deploy-pages from 1 to 3

---

package.json
pnpm-lock.yaml

Upgrade prettier from 2.8.8 to v3.1.1 to fix failing prettier check

---

src/components/ArchiveSections.astro

Archiveページの区間が1つしかない

---

.github/workflows/check-and-build.yml

Add test building in pull-requests

---

.github/workflows/deploy.yml

Reverts vim-jp/ekiden#241
間違って、レビューでOKしちゃったので、こちら一旦戻しで。

Revert "Bump actions/deploy-pages from 3 to 4"

---

package.json
pnpm-lock.yaml
src/components/Footer.astro
src/components/Header.astro
src/components/HeaderLink.astro
src/layouts/Base.astro
src/pages/archives.astro
src/pages/index.astro
src/pages/ranking.astro
src/pages/ranking/[section].astro
src/pages/runners/[runner].astro
tailwind.config.cjs

併せて、Google Fontsを@importする形式からfontsourceを使うように修正

update: Article.astro以外で@applyやstyleタグを除去

---

src/layouts/Base.astro

ページ遷移をSPAみたいにアニメーションをさせるものです。
https://github.com/vim-jp/ekiden/assets/61523777/2c977197-128a-47a8-a92b-2e41147491a2
View Transition APIをサポートしていなブラウザへはAstroが自動的にフォールバックしてくれるようなので、問題は起きないはずです。
参考: https://docs.astro.build/ja/guides/view-transitions/

View Transition を追加

---

src/components/SeasonList.astro
src/layouts/Base.astro
src/pages/archives.astro
src/pages/archives/[section].astro
src/pages/index.astro
src/pages/ranking.astro
src/pages/ranking/[section].astro
src/pages/runners/[runner].astro
tsconfig.json

- import aliasを設定しました。import時の見栄えが良くなるはずです

refactor: use import alias

---

src/layouts/Base.astro

ｺﾞﾒﾝﾅｻｲ
コミットをいじった時に消してしまってました..

fix: footerを最下部に固定

---

src/components/RankChart.svelte

tree shaking前
```
16:27:04 [vite] dist/_astro/RankChart.mXRHUyeD.js  214.70 kB │ gzip: 74.11 kB
```
tree shaking後
```
16:26:58 [vite] dist/_astro/RankChart.GQHeUs36.js  145.13 kB │ gzip: 51.56 kB
```

chartJS にtree shakingを適用

---

.prettierrc.mjs
src/components/RankChart.svelte

prettierでsvelteのfileをformatするようにしました。

fix prettier config: apply format to svelte file

---

src/components/SeasonList.astro
src/lib/article.ts
src/pages/archives/[section].astro
src/pages/archives/index.astro
src/pages/index.astro
src/pages/ranking/[section].astro
src/pages/ranking/index.astro
src/pages/rss.xml.ts
src/pages/runners/[runner].astro

`getArticles`関数を作ってcontent.jsonを読み込む処理を共通化する

Implement `getArticles` to parse content.json

---

src/pages/rss.xml.ts

すいません、レビュー漏れてました :bow:
表題のとおりです。

fix: RSS の出力が最も古い10記事になっていたため最新10記事に修正

---

.prettierrc.mjs
package.json
pnpm-lock.yaml
src/components/Article.astro
src/components/Footer.astro
src/components/Header.astro
src/components/HeaderLink.astro
src/components/SeasonList.astro
src/layouts/Base.astro
src/pages/404.astro
src/pages/archives/[section].astro
src/pages/archives/index.astro
src/pages/index.astro
src/pages/ranking/index.astro
src/pages/runners/[runner].astro

Tailwind Prettierの導入
class名をいい感じにformatしてくれる
https://github.com/tailwindlabs/prettier-plugin-tailwindcss

add tailwind prettier plugin

---

.prettierrc.mjs
package.json
pnpm-lock.yaml

related: #331
astroのprettierでもsvelteはformatできるのだが、専用のpluginを入れるのがbetterらしいので追加する
#331 がmergeされたら作業を再開する

add prettier-plugin-svelte

---

src/pages/runners/[runner].astro

related to https://github.com/vim-jp/ekiden/pull/330
輪ごむさんの指摘通り、　`&&`を使ったものに修正

fix: use && for conditional rendering

---

src/lib/article.ts

`getArticle`関数の戻り値を用いて`ProcessedArticle`を定義する

define ProcessedArticle type

---

package.json
pnpm-lock.yaml
src/components/ArticleInArchive.astro
src/pages/archives/[section].astro
src/pages/archives/index.astro
src/pages/runners/[runner].astro

Archiveやrunnerのページで表示されている記事のcomponentをまとめる

create `ArticleInArchive` component

---

.github/workflows/check-and-build.yml
.github/workflows/deploy.yml
package.json
pnpm-lock.yaml

for `engines` at package.json, c.f. https://pnpm.io/package_json#engines

Upgrade pnpm version to 9

---

.github/workflows/auto-merge-dependabot.yml

c.f. https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

Enable auto-merge PRs (updating patch-version) made by dependabot

---

astro.config.mjs

This pull request updates URL as follows.
Actual: `/ekidenrss.xml`
Expected: `/ekiden/rss.xml`

Fix rss link

---

src/components/ArticleInArchive.astro
src/components/RecordCard.astro
src/components/SeasonList.astro
src/layouts/Base.astro
src/pages/index.astro
src/pages/runners/[runner].astro
src/pages/statistics/index.astro
tailwind.config.cjs

Unified design

---

package.json

feat(package.json): private trueを設定

---

.github/workflows/update-article.yml
scripts/update-article.ts

Closes #409 
キャンセルのための条件を以下のように変更する。
> Issue が Close された際に、以下のいずれかが満たされていること。
>
> - 記事URLがない
> - 投稿予定日付（JST）より前
> - `Close as not planned`
変更に伴い、いくつかリファクタリングをしている。

Change cancel condition

---

pnpm-lock.yaml

fix(deps): Correct pnpm lock format

---

scripts/update-article.ts

deno.land -> jsr
jsr でのpackage 情報はこちら
https://jsr.io/@std/fmt/doc/printf/~/sprintf

feat(scripts/update-article): deno.land -> jsr

---

src/components/ArticleInArchive.astro
src/components/HeaderLink.astro
src/components/RecordCard.astro
src/components/SeasonList.astro
src/env.d.ts

共通のclassがわかりやすいように `class:list` を使ってみる

class:list を多用して可読性を上げていく

---

src/components/HeaderLink.astro
src/pages/statistics/index.astro

- **fix(HeaderLink): pタグのみ下線をつけるように修正 レビューで見逃がしてしまいました。。**
- **fix(statistics): slugが誤っていたので修正**

HeaderLinkのクラス修正+統計ページのslug修正

---

package.json
pnpm-lock.yaml
src/components/HeaderLink.astro
src/layouts/Base.astro
src/lib/url.ts
src/pages/archives/[section].astro
src/pages/archives/index.astro
src/pages/ranking/[section].astro
src/pages/ranking/index.astro
src/pages/runners/[runner].astro
src/pages/statistics/index.astro

slugをわたす側で毎回気をつけるのは大変そうなので、Base.astro内でslashがなかったら自動でつける方が良いと思いました

feat: slugの末尾slash追加を`Base.astro` の受け手側で処理する

---

src/layouts/Base.astro

皆さんの意見をお聞きしたいです。
気にならない人が多いのであれば、closeしてしまって問題ありません。
before:
https://github.com/user-attachments/assets/bd01c46e-1ff7-4301-863a-1970a2dae371
after:
https://github.com/user-attachments/assets/9d8a31eb-bdec-4b90-8412-d59f9c7cd78d

feat: スクロールバーの常時表示

---

scripts/update-article.ts
src/components/RankChart.svelte
src/lib/article.ts
src/lib/type.ts
src/pages/rss.xml.ts

`getArticles` の型を修正

---

package.json

- engine fieldはもう使わないので削除
- pnpm以外でinstallしたときにエラーが出るようにscriptを追加

manage package.json's fields

---

.gitignore
package.json

feat(package.json): prettierとeslintのキャッシュを有効にする

---

src/components/HeaderLink.astro
uno.config.ts

underlineをview transitionでいい感じに動かします
https://github.com/user-attachments/assets/f49c67ac-1dc4-4542-b752-af6d0e129ce4

feat(HeaderLink.astro): move underline with view transition api

---

src/components/HeaderLink.astro
src/components/SeasonList.astro

最近知ったのですが、`href`のない`a`タグは roleなし、つまり `div` や `span` と同じ役割になるので、a tagを使うかどうかの分岐はいらないらしい
https://developer.mozilla.org/ja/docs/Web/HTML/Element/a#%E6%8A%80%E8%A1%93%E7%9A%84%E6%A6%82%E8%A6%81

 aタグの分岐を除く

---

src/components/RecordCard.astro
src/pages/statistics/index.astro

https://github.com/user-attachments/assets/bb0b559f-bf74-4568-8cf2-44d6fab9c968

feat(statistics): 最多投稿者をrunnsersページへのリンクに変更

---

pnpm-lock.yaml

pnpm-lockがdependabotで自動更新できなくなったため修正 from: #713 #714 #715 #719

fix: Update pnpm-lock.yaml

---

.github/CODEOWNERS
README.md

**CAUTION: Reviewerで指名している全員からApprove(承諾)もらうまでMergeしない**
closes: #228

feat(docs): Specify core-maintainers in README and CODEOWNERS

---

.github/CODEOWNERS

from: https://vim-jp.slack.com/archives/C04S13HHVQS/p1735550546060999

feat: Specify empty onwers to avoid notifications by dependabot PRs

---

package.json
pnpm-lock.yaml
src/layouts/Base.astro

- astroをv5に上げました
- [ClientRouter](https://docs.astro.build/en/guides/view-transitions/)を`ViewTransition`に変わるものとして置き換えました

update to astro v5

---

src/components/RankChart/RankChart.svelte
src/components/RankChart/utils.ts

一応あってそう
#866 がmergeされたらrebaseしてdraft外す

ランキングの計算ロジックをモダンな記法に修正

---

src/components/Footer.astro
src/components/Header.astro

画像の読み込みの最適化
