vim-jp/ekiden

src/pages/index.astro
ドキュメントにて問題のクラスに対してCSSを当てて良いと明記されていたため、index.astor内へCSSルールを追加いたしました。
参照：https://fullcalendar.io/docs/css-customization
=> 日付ラベルが見えなくなる問題の解消

src/components/Calendar.tsx
エントリー可能な日が週 3 日なので、30 日だと 12,13 日分程度しかエントリーができない。
もっと先まで埋まっても大丈夫なように、60 日先までエントリー可能にする。
(※カレンダーを使わずに Issue に直接日付を入れれば、何日先でもエントリーは可能ではある)
=> Change REGISTRATION_LINK_DISPLAY_DAYS to 60

.github/workflows/deploy.yml
URL が事前登録されていた場合に、
- リストのタイトルにリンクを追加
- RSS にエントリーを追加
を行うため、公開日の月水金の 0 時(JST) に自動でデプロイを行う。
Closes #25
=> Auto deploy on publish day

src/components/Article.astro, src/pages/index.astro
現在使用している書体が読みづらい（特に欧文）という意見が多かったため、デザインに大きく影響する「Vim 駅伝」ヘッダや見出し、日付の書体だけ現状を維持し、それ以外の本文の書体を総称ファミリーの `sans-serif` としました。
また、フォントの変更によって概要説明欄のまとまりが悪くなったように感じられたため、
よりメリハリをつけるため余白を若干調整しています。
sans-serif を Noto Sans CJK JP で表示するよう設定している私のブラウザ上だと、以下のように表示されます。
=> 本文の書体を総称ファミリーで指定

src/components/Article.astro, src/layouts/Base.astro, src/pages/index.astro
新着記事のタイトルをトップに表示し、新着記事へのリンクを冒頭に追加しました。
それに伴ってレイアウトを少し変更しています。
記事のリンク先に直接飛ぶのではなく、Vim 駅伝トップページの特定の位置までスクロールするようにしています。
https://user-images.githubusercontent.com/48883418/232082893-e4b1450c-8848-450e-891f-ffc07b236de4.mov
=> 新着記事へのリンクを冒頭に追加

src/components/HeaderLink.astro
ヘッダーの「トップーページ」と「アーカイブ」の位置が次の動画のようにページごとに少し異なっています。
https://github.com/vim-jp/ekiden/assets/61523777/1a8369e9-bfb5-49c4-8810-4442c7d2c632
修正後:
https://github.com/vim-jp/ekiden/assets/61523777/99b545b5-f9c4-4723-b52d-b4eae0432b36
=> fix: HeaderLink position is misaligned

astro.config.mjs, package.json, pnpm-lock.yaml, src/components/ArchiveSections.astro, src/components/Header.astro, src/layouts/Base.astro, src/pages/archives.astro, src/pages/archives/[section].astro
区間（年度・季節）ごとに分けて表示するアーカイブページを新たに作成し、
各アーカイブページの冒頭にそれらへのリンクが付くようにしました。
それに伴い、ページのパスも `/ekiden/archive` から `/ekiden/archives/` へとリネームしました（そのほうが自然な気がしたので）。
なお、`/ekiden/archive` は `/ekiden/archives/` へとリダイレクトするよう設定を追加してます。
`/ekiden/archives/` の様子
`/ekiden/archives/2023summer` の様子
=> 区間ごとに分けたArchiveページの追加

astro.config.mjs
https://vim-jp.org/ekiden/rss.xmlが404になっている。
astro.config.mjsにて定義されているbaseはtrailingSlashの影響を受けます。
defaultがignoreなので、alwaysに設定することでもしかすると改善するのではないか？と考えています。
https://docs.astro.build/en/reference/configuration-reference/#base
何故推測なのかというと、ローカルの開発環境では該当の問題が発生しないからです。
=> Update astro.config.mjs to include trailing slash option

.github/workflows/check-article.yml, .github/workflows/update-article.yml
駅伝公開後 (つまり，ボットによって 'completed' としてissueが閉じされたあと)，issueの内容を変更した場合でも，その変更を追従できるようにしました．この手のGitHub Actionsはテストができないので，テストせずに投稿することになり恐縮ですが，よろしくお願いします．
=> 記事のURLを更新できるようにしたい．

astro.config.mjs, package.json, pnpm-lock.yaml, src/components/Articles.astro, src/components/Header.astro, src/components/RankChart.svelte, src/components/SeasonList.astro, src/layouts/Base.astro, src/pages/archives.astro, src/pages/archives/[section].astro, src/pages/ranking.astro, src/pages/ranking/[section].astro
ランキングページを追加しました。
- グラフ描画のため chart.js を、グラフのコンポーネントを追加するため Svelte を導入しました。
- ひとまず10位の人まで表示する仕様となっています。
- アーカイブページ同様、季ごとのランキングも表示できるようにしました。
- 本当はグラフをクリックするとその人の記事一覧に飛ぶ、みたいなのがやりたかったんですが、実現する簡単な方法が調べた限り無さそうだったので一旦諦めてます。
@staticWagomU アドバイスありがとうございます！
=> ランキングページの追加

src/components/RankChart.svelte, src/pages/ranking/[section].astro
表題のとおりです。
- グラフの横軸の目盛りを1にすることで "1.5" みたいな表示が出るのを防いでいます。
- 将来的には総合ランキングの目盛りが細かくなりすぎるかもしれませんが、それはそうなった時に考えます。
- published なものだけがランキングに計上されるように修正しました。
- もともと総合ランキングはそうなっていたのですが、季ごとのほうがそうなってませんでした。
=> fix: グラフの目盛りを1に変更& published なものだけ載るよう修正

src/components/RankChart.svelte
https://github.com/vim-jp/ekiden/assets/34824645/81c83219-9b19-42ed-bf81-839143448621
動画に残し忘れましたが、10位の人をクリックしても遷移することを確認しています。
=> feat: グラフのバーをクリックすることで走者のページへ遷移できるようにした

src/layouts/Base.astro
駅伝記事のタイトルの長さに依って親要素の width が変化しています。
(添付画像を参照)
問題となっている要素の width を 100% に指定することで解決します。
短い場合：
長い場合：
理想の挙動：
=> メインの要素の width が子要素に依存している

src/components/SeasonList.astro
rankingのsection viewをresponsiveにしました
before
after
=> make section list responsive

src/pages/runners/[runner].astro
=> hidden classで要素を隠す代わりに条件レンダリングを使う

package.json, pnpm-lock.yaml, tsconfig.json
参照: https://docs.astro.build/ja/guides/typescript/#%E6%BA%96%E5%82%99
typescriptからastroを読み込んだ時に、neovimでエラーになることがあったのでtypescriptのプラグインを導入
=> install @astrojs/ts-plugin

src/components/ArticleInArchive.astro
1. Duplicate a link divided.
2. Runner's link moved left to right.
3. Add runner icon.
Issuesの#338対応。
重複しているAタグの対応。
筆者名を左端から右端に移動し、ついでにランナーアイコンをつけてみました。
PC版スクリーンショット
SP版スクリーンショット
=> [Update] Update Archive page design.

src/components/Header.astro, src/components/RecordCard.astro, src/lib/article.ts, src/pages/statistics/index.astro, tailwind.config.cjs
「最多投稿者」の箇所は、複数の人の表示に対応しています。
- `tailwind.config.cjs`にmonospaceのためのフォントの設定を追加
- `src/lib/articles.ts`のJSDocのコメントが間違っている問題を修正
=> 「統計」のページを追加

.github/workflows/check-article.yml
check-article は該当 Issue が閉じられていた場合は一切動かす必要がない。
This reverts commit c83a2ca03d06a234f90b5595d587acbe884667d2.
Closes #433
=> Revert "abort if issue was closed not as "completed""

scripts/update-article.ts
Issues の description から JSON のエントリーを生成する際、description のセクションが複数行あった場合に最初の 1 行しか参照されない問題がありました。
大抵は 1 行しかないので問題になっていませんでしたが、一部の文字をエスケープするためにコードブロックなどを使おうとすると問題になりました。
この変更では複数行の対応をするとともに、content からは改行を消すようにしました。
=> Fix section extracting with multiline

src/components/RankChart.svelte, src/components/SeasonList.astro, src/lib/article.ts
本番環境では自動的に末尾スラッシュが付くが、開発環境では404へ飛ばされるため
=> trailingslashを追加

scripts/update-article.ts
Content が複数行だった場合にマッチに失敗してエラーが出ていたのを修正する。
=> Fix unescapeContent() with multiline

.github/workflows/update-article.yml
If the command fails, a step fails immediately.
In this case, `MESSAGE` does not output.
As a result, the job fails due to malformed output file.
To prevent this, change the command so that it always succeeds.
=> Fix error handling in update-article

src/components/ArticleInArchive.astro
afterのように最後の要素にはborderがつかないように修正
before 
after
=> 隣接兄弟要素を使う実装に修正

eslint.config.js, package.json, pnpm-lock.yaml
- #516 で、fileがうまく指定できてなかった
- eslint-plugin-astroがflat configになってからはいいかんじに設定してくれているので設定を削除
- svelteのeslintもeslint-plugin-astroで対処してくれているので導入の必要がなかったようです
=> fix(eslint): eslint-plugin-astroが内部で色々やってくれてるのでfix

.github/workflows/check-and-build.yml, .github/workflows/deploy.yml, .npmrc, package.json
pnpmの機能でnodeとpnpmのversionを管理することのメリットは以下の通り
- 公式で推奨されている
- https://github.com/pnpm/pnpm/releases/tag/v9.7.0
- https://pnpm.io/ja/npmrc#manage-package-manager-versions
- 各々のlocal環境でもpackage.jsonで指定されているpnpm/nodeのバージョンを使うように強制できる
- GitHub Actionsでも自動的に該当のversionのnodeが落ちてくる([参考](https://github.com/vim-jp/ekiden/actions/runs/10930812387/job/30344523385?pr=598#step:4:7))
ついでにpnpmのversionを9.10にし、nodeのバージョンも20.17.0にしました
=> pnpmの機能でpnpmとnodeのバージョンを管理する

.github/workflows/check-and-build.yml
=> fix(ci): lintとbuildをステップごとに分ける

.github/workflows/update-article.yml
SSIA, setup-denoは #648 でv2対応済み
=> build(deps): bump deno v1.46.1 to v2.0.0

scripts/update-article.ts
#724 で変更したIssueテンプレートにて「注意事項の確認」セクションを設けたが、
Article情報更新のActionでセクションのチェックが例外に振り分けられてしまった。
当該セクションをnoop扱いで退避する。
=> fix(update-article): allow new section "注意事項の確認" in the issue

src/components/Articles.astro, src/lib/schedule.ts
- **chore: 現行のスケジュール基準を明記**
- **feat(schedule): prepare schedule generator**
- **fix(top): スケジュールに空き枠を表示する**
fix: #742
=> トップページの空き枠を確保する

src/components/ArticleMonth.astro, src/components/Footer.astro, src/components/Header.astro
このプルリクエストには、スタイリングを単純化し標準化するために、複数のコンポーネントのCSSクラスにいくつかの変更が含まれています。最も重要な変更は `ArticleMonth`、`Footer`、`Header` コンポーネントの更新です。
スタイリングの更新
* [`src/components/ArticleMonth.astro`](diffhunk://#diff-31ed6df4300cbf0ee72875c0791cf8ad8b0c0a057e927f6adaefd539f3b34ec1L7-R19): 特定のピクセル値をTailwind CSSユーティリティクラスに置き換えることで、paddingとwidthクラスを簡素化。
* [`src/components/Footer.astro`](diffhunk://#diff-9f7d7eae483a60a6aa76bcb68acc770e441d441ce02d414637694162983e6159L35-R35): Tailwind CSSユーティリティクラスを使用したライセンス画像の寸法を更新し、一貫性を持たせた。
* [`src/components/Header.astro`](diffhunk://#diff-cef92c86af879f90a7ac8087da782381ed31160251d9960fe59f7ee29389a9beL24-R24): 特定の高さと幅のクラスを、ロゴ画像用の単一のユーティリティ・クラスに置き換えた。
=> pxを用いたclass指定をやめて、tailwind標準の数値によるサイズ指定を行う

package.json, pnpm-lock.yaml, src/components/RankChart.svelte, src/components/RankChart/RankChart.svelte, src/components/RankChart/index.ts, src/components/RankChart/types.ts, src/components/RankChart/utils.ts, src/pages/ranking/[section].astro, src/pages/ranking/index.astro
rankingのグラフが表示されていなかったので修正
~~`client:only='svelte`じゃなくなった？教えて詳しい人！ (多分 @staticWagomU さん詳しそう~~
本来ならば個別のPRに分けるべきですが、一気にやってしまいました
- svelte-chartjsがメンテされていないので依存から排除。直接chatjsを叩きます
- svelte5に移行
- Componentのfileの行数が長く見通しが悪いため、データ整形の関数を別fileに逃しました
=> RankingページでSvelteのComponentが表示されない問題を修正 & Svelte5にアプデ

src/components/Footer.astro
ここをpxで指定していたのはおそらく画像が意図せず小さくなってしまっていたからだと推測
なので、画像をshrinkさせないように修正
参考: https://github.com/vim-jp/ekiden/pull/856#discussion_r1934788264
参考: https://tailwindcss.com/docs/flex-shrink#preventing-items-from-shrinking
=> refactor(Footer.astro): `shrink-0`を用いることでクリエイティブ・コモンズの画像にサイズを指定せずに画像を等倍で表示する

src/components/ArticleMonth.astro
駅伝のトップ画面のx月の上下にあったの謎のpaddingを直しました
before
after
=> fix padding at ArticleMonth component

src/components/Header.astro
before: ![image](https://github.com/user-attachments/assets/be24114d-8df7-48d7-a2f9-9bb31224eb53)
after: ![image](https://github.com/user-attachments/assets/9033b2b2-cfd0-496a-9233-2abf738ec6f8)
As a just idea.
I am a little doubtful that this is solution for the problem.
for: vim-jp/ekiden#908
=> feat: put a link for the repository on the header

src/pages/index.astro
index ページに自分の予約を確認できるページ(GitHub issue)へのリンクを追加しました。
See: #908
=> 「自分の予約一覧(GitHub issue)」へのリンクを追加。

package.json, pnpm-lock.yaml, pnpm-workspace.yaml
https://pnpm.io/package_json#devenginesruntime
`devEngine.runtime`でnodeのランタイムを管理するようにしました。
- より標準の方法
- lockfileにnodeのバージョンが記載される
などのメリットがあります
=> chore: update pnpm and use devEngines.runtime to manage node runtime
